// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP25
#define USB_VBUS_PIN GP24
#define SERIAL_USART_FULL_DUPLEX

#define I2C1_SDA_PIN GP2
#define I2C1_SCL_PIN GP3

#define AUDIO_PIN GP8
#define AUDIO_PWM_DRIVER PWMD4
#define AUDIO_PWM_CHANNEL RP2040_PWM_CHANNEL_A
#define AUDIO_INIT_DELAY
#define STARTUP_SONG SONG(M__NOTE(_C7, 30), M__NOTE(_C6, 30))

#define I2C_DRIVER I2CD1
#define OLED_DISPLAY_128X64

#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_ROTATION_180
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
